### ISSUE TITLE
Spamlar için adres girme zorunluluğu

### ISSUE THREAD

**Issue by MustafaCQN** [YusufOzmen01/veri-toplama-backend#4]
Bu issue front-end için aslında ancak repoyu bilmediğimiz için buraya açıyorum, lütfen siz iletin

veri-toplama daki arkadaşlarla spam postlarını işaretlerken adres girme zorunluluğu çıkıyor ve birşeyler sallıyor veya "-" giriyoruz. bunu düzeltirsek sonradan gelicek arkadaşlar daha rahat adapte olabilirler

**Comment by furknozg** [comment]
Front end tarafında zaten çözülmüştür
